# Generated by Django 4.1.6 on 2023-03-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0002_post__preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('a', 'article'), ('n', 'news')], default='a', max_length=1),
        ),
    ]
