# Generated by Django 4.1.6 on 2023-04-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0006_remove_category_subscriber_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
